"""Add column image_link to advert model

Revision ID: adcd1d43462d
Revises: 14478cd09784
Create Date: 2021-03-03 01:19:29.513972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adcd1d43462d'
down_revision = 'addd1d43462d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advert', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advert', 'rating')
    # ### end Alembic commands ###
